import React from "react"
import IngredientsList from "./components/IngredientsList"
import ClaudeRecipe from "./components/ClaudeRecipe"
import { getRecipeFromMistral } from "./ai"

export default function Main() {

    // Ingredients State
    // Ingredients provided by the user will be added to and removed from an array
    const [ingredients, setIngredients] = React.useState([])

    // Recipe State
    // For rendering the markdown generated by the AI
    const [recipe, setRecipe] = React.useState("")

    // Loading state
    // So the loading animation plays as the AI forms a reponse
    const [loading, setLoading] = React.useState(false)

    // Get Recipe function
    async function getRecipe() {
        setLoading(true)
        setRecipe("");
        try {
            const recipeMarkdown = await getRecipeFromMistral(ingredients);
            setRecipe(recipeMarkdown);
        } catch (err) {
            console.error("Failed to get recipe:", err);
        } finally {
            setLoading(false)
        }
    }

    // Add ingredient
    function addIngredient(formData) {
        const newIngredient = formData.get("ingredient")
        if (newIngredient === "") {}
        else {setIngredients(prevIngredients => [...prevIngredients, newIngredient])}
    }

    // Remove ingredient
    function removeIngredient() {
        setIngredients(prevIngredients => prevIngredients.slice(0, -1))
        setRecipe("");
    }

    return (
        <main>
            {/* Textbox, add & remove buttons */}
            <form
                onSubmit={(e) => {
                    e.preventDefault();
                    const formData = new FormData(e.target);
                    addIngredient(formData);
                    e.target.reset();
                }}
                className="add-ingredient-form"
                >
                <input
                    type="text"
                    placeholder="e.g. oregano"
                    aria-label="Add ingredient"
                    name="ingredient"
                />
                <button type="submit" className="add-btn">Add</button>
                <button type="button" className="remove-btn" onClick={removeIngredient}>Remove</button>
            </form>

            {/* Render list of ingredients */}
            {ingredients.length > 0 &&
                <IngredientsList
                    ingredients={ingredients}
                    getRecipe={getRecipe}
                />
            }

            {/* Render loading animation */}
            {loading && 
            <div className="loading-text">
                Loading recipe<span className="dots"></span>
            </div>}

            {/* Render the recipe markdown */}
            {recipe && <ClaudeRecipe recipe={recipe} />}
        </main>
    )
}